import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>World Ranks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2 className={styles.title}>World Ranks</h2>

      <div className={`${styles.search}`}>
        <input className="form-control" placeholder="Filter by name, region or subregion" />
      </div>

    </div>
  )
}
